-- Expansão completa do plano de contas financeiro
-- Baseado no plano existente + lacunas identificadas para cenário amplo

WITH seed (codigo, nome, tipo, natureza) AS (
  VALUES
    -- 1. ATIVO
    ('1', 'Ativo', 'Ativo', 'Devedora'),
    ('1.1', 'Ativo Circulante', 'Ativo Circulante', 'Devedora'),
    ('1.1.01', 'Caixa e Equivalentes de Caixa', 'Disponibilidades', 'Devedora'),
    ('1.1.01.01', 'Caixa', 'Disponibilidades', 'Devedora'),
    ('1.1.01.02', 'Bancos Conta Movimento', 'Disponibilidades', 'Devedora'),
    ('1.1.01.03', 'Aplicações Financeiras de Liquidez Imediata', 'Disponibilidades', 'Devedora'),
    ('1.1.01.04', 'Numerários em Trânsito', 'Disponibilidades', 'Devedora'),
    ('1.1.01.05', 'Cartões a Receber', 'Disponibilidades', 'Devedora'),

    ('1.1.02', 'Contas a Receber', 'Ativo Circulante', 'Devedora'),
    ('1.1.02.01', 'Clientes Nacionais', 'Ativo Circulante', 'Devedora'),
    ('1.1.02.02', 'Clientes Internacionais', 'Ativo Circulante', 'Devedora'),
    ('1.1.02.03', 'Duplicatas a Receber', 'Ativo Circulante', 'Devedora'),
    ('1.1.02.04', 'Adiantamentos a Clientes', 'Ativo Circulante', 'Devedora'),
    ('1.1.02.99', 'Perdas Estimadas com Créditos de Liquidação Duvidosa', 'Ativo Circulante', 'Credora'),

    ('1.1.03', 'Tributos e Créditos a Recuperar', 'Ativo Circulante', 'Devedora'),
    ('1.1.03.01', 'ICMS a Recuperar', 'Tributário', 'Devedora'),
    ('1.1.03.02', 'PIS a Recuperar', 'Tributário', 'Devedora'),
    ('1.1.03.03', 'COFINS a Recuperar', 'Tributário', 'Devedora'),
    ('1.1.03.04', 'ISS a Recuperar', 'Tributário', 'Devedora'),
    ('1.1.03.05', 'INSS a Compensar', 'Tributário', 'Devedora'),
    ('1.1.03.06', 'IRPJ/CSLL por Estimativa a Compensar', 'Tributário', 'Devedora'),

    ('1.1.04', 'Estoques', 'Ativo Circulante', 'Devedora'),
    ('1.1.04.01', 'Estoque de Mercadorias', 'Ativo Circulante', 'Devedora'),
    ('1.1.04.02', 'Estoque de Materiais de Consumo', 'Ativo Circulante', 'Devedora'),
    ('1.1.04.03', 'Estoque em Trânsito', 'Ativo Circulante', 'Devedora'),
    ('1.1.04.99', 'Provisão para Perdas de Estoque', 'Ativo Circulante', 'Credora'),

    ('1.1.05', 'Outros Créditos de Curto Prazo', 'Ativo Circulante', 'Devedora'),
    ('1.1.05.01', 'Adiantamento a Fornecedores', 'Ativo Circulante', 'Devedora'),
    ('1.1.05.02', 'Adiantamento a Colaboradores', 'Ativo Circulante', 'Devedora'),
    ('1.1.05.03', 'Despesas Antecipadas', 'Ativo Circulante', 'Devedora'),
    ('1.1.05.04', 'Depósitos Judiciais de Curto Prazo', 'Ativo Circulante', 'Devedora'),

    ('1.2', 'Ativo Não Circulante', 'Ativo Não Circulante', 'Devedora'),
    ('1.2.01', 'Realizável a Longo Prazo', 'Ativo Não Circulante', 'Devedora'),
    ('1.2.01.01', 'Depósitos Judiciais', 'Ativo Não Circulante', 'Devedora'),
    ('1.2.01.02', 'Empréstimos Concedidos', 'Ativo Não Circulante', 'Devedora'),
    ('1.2.01.03', 'Créditos com Partes Relacionadas', 'Ativo Não Circulante', 'Devedora'),

    ('1.2.10', 'Investimentos', 'Investimentos', 'Devedora'),
    ('1.2.10.01', 'Participações Societárias', 'Investimentos', 'Devedora'),
    ('1.2.10.02', 'Propriedades para Investimento', 'Investimentos', 'Devedora'),

    ('1.2.20', 'Imobilizado', 'Imobilizado', 'Devedora'),
    ('1.2.20.01', 'Equipamentos de Informática', 'Imobilizado', 'Devedora'),
    ('1.2.20.02', 'Móveis e Utensílios', 'Imobilizado', 'Devedora'),
    ('1.2.20.03', 'Instalações', 'Imobilizado', 'Devedora'),
    ('1.2.20.04', 'Máquinas e Equipamentos', 'Imobilizado', 'Devedora'),
    ('1.2.20.05', 'Veículos', 'Imobilizado', 'Devedora'),
    ('1.2.20.99', 'Depreciação Acumulada', 'Imobilizado', 'Credora'),

    ('1.2.30', 'Intangível', 'Intangível', 'Devedora'),
    ('1.2.30.01', 'Softwares', 'Intangível', 'Devedora'),
    ('1.2.30.02', 'Marcas e Patentes', 'Intangível', 'Devedora'),
    ('1.2.30.03', 'Desenvolvimento de Sistemas', 'Intangível', 'Devedora'),
    ('1.2.30.99', 'Amortização Acumulada', 'Intangível', 'Credora'),

    -- 2. PASSIVO
    ('2', 'Passivo', 'Passivo', 'Credora'),
    ('2.1', 'Passivo Circulante', 'Passivo Circulante', 'Credora'),
    ('2.1.01', 'Fornecedores', 'Passivo Circulante', 'Credora'),
    ('2.1.01.01', 'Fornecedores Nacionais', 'Passivo Circulante', 'Credora'),
    ('2.1.01.02', 'Fornecedores Internacionais', 'Passivo Circulante', 'Credora'),
    ('2.1.01.03', 'Fretes a Pagar', 'Passivo Circulante', 'Credora'),

    ('2.1.02', 'Obrigações Trabalhistas', 'Passivo Circulante', 'Credora'),
    ('2.1.02.01', 'Salários a Pagar', 'Passivo Circulante', 'Credora'),
    ('2.1.02.02', 'Pró-labore a Pagar', 'Passivo Circulante', 'Credora'),
    ('2.1.02.03', 'INSS a Recolher', 'Passivo Circulante', 'Credora'),
    ('2.1.02.04', 'FGTS a Recolher', 'Passivo Circulante', 'Credora'),
    ('2.1.02.05', 'Férias a Pagar', 'Passivo Circulante', 'Credora'),
    ('2.1.02.06', '13º Salário a Pagar', 'Passivo Circulante', 'Credora'),
    ('2.1.02.07', 'Encargos Sociais', 'Passivo Circulante', 'Credora'),
    ('2.1.02.08', 'Benefícios', 'Passivo Circulante', 'Credora'),

    ('2.1.03', 'Obrigações Fiscais', 'Passivo Circulante', 'Credora'),
    ('2.1.03.01', 'Simples Nacional a Recolher', 'Tributário', 'Credora'),
    ('2.1.03.02', 'ISS a Recolher', 'Tributário', 'Credora'),
    ('2.1.03.03', 'ICMS a Recolher', 'Tributário', 'Credora'),
    ('2.1.03.04', 'PIS/COFINS a Recolher', 'Tributário', 'Credora'),
    ('2.1.03.05', 'IRRF a Recolher', 'Tributário', 'Credora'),
    ('2.1.03.06', 'PCC Retido a Recolher', 'Tributário', 'Credora'),
    ('2.1.03.07', 'IRPJ a Recolher', 'Tributário', 'Credora'),
    ('2.1.03.08', 'CSLL a Recolher', 'Tributário', 'Credora'),

    ('2.1.04', 'Provisões e Competência', 'Passivo Circulante', 'Credora'),
    ('2.1.04.01', 'Despesas de Competência a Pagar', 'Passivo Circulante', 'Credora'),
    ('2.1.04.02', 'Provisão de Bônus e Comissões', 'Passivo Circulante', 'Credora'),
    ('2.1.04.03', 'Provisão para Contingências', 'Passivo Circulante', 'Credora'),

    ('2.1.05', 'Receitas Diferidas', 'Passivo Circulante', 'Credora'),
    ('2.1.05.01', 'Receita Diferida de Assinaturas', 'Passivo Circulante', 'Credora'),
    ('2.1.05.02', 'Receita Antecipada de Projetos', 'Passivo Circulante', 'Credora'),

    ('2.1.20', 'Empréstimos e Financiamentos CP', 'Passivo Circulante', 'Credora'),
    ('2.1.20.01', 'Empréstimos de Curto Prazo', 'Passivo Circulante', 'Credora'),
    ('2.1.20.02', 'Juros a Apropriar CP', 'Passivo Circulante', 'Credora'),

    ('2.2', 'Passivo Não Circulante', 'Passivo Não Circulante', 'Credora'),
    ('2.2.01', 'Empréstimos e Financiamentos LP', 'Passivo Não Circulante', 'Credora'),
    ('2.2.01.01', 'Empréstimos e Financiamentos de Longo Prazo', 'Passivo Não Circulante', 'Credora'),
    ('2.2.01.02', 'Debêntures a Pagar', 'Passivo Não Circulante', 'Credora'),
    ('2.2.02', 'Provisões de Longo Prazo', 'Passivo Não Circulante', 'Credora'),
    ('2.2.02.01', 'Contingências Trabalhistas', 'Passivo Não Circulante', 'Credora'),
    ('2.2.02.02', 'Contingências Cíveis', 'Passivo Não Circulante', 'Credora'),
    ('2.2.02.03', 'Contingências Tributárias', 'Passivo Não Circulante', 'Credora'),
    ('2.2.03', 'Receitas Diferidas LP', 'Passivo Não Circulante', 'Credora'),
    ('2.2.03.01', 'Receita Diferida de Longo Prazo', 'Passivo Não Circulante', 'Credora'),

    -- 3. PATRIMÔNIO LÍQUIDO
    ('3', 'Patrimônio Líquido', 'Patrimônio Líquido', 'Credora'),
    ('3.1', 'Capital Social', 'Patrimônio Líquido', 'Credora'),
    ('3.2', 'Reservas de Lucros', 'Patrimônio Líquido', 'Credora'),
    ('3.3', 'Ajustes de Avaliação Patrimonial', 'Patrimônio Líquido', 'Credora'),
    ('3.4', 'Lucros ou Prejuízos Acumulados', 'Patrimônio Líquido', 'Credora'),
    ('3.5', 'Dividendos/JCP a Distribuir', 'Patrimônio Líquido', 'Credora'),
    ('3.6', 'Ajustes de Exercícios Anteriores', 'Patrimônio Líquido', 'Credora'),

    -- 4. RECEITAS
    ('4', 'Receitas', 'Receita', 'Credora'),
    ('4.1', 'Receitas Operacionais', 'Receita Operacional', 'Credora'),
    ('4.1.01', 'Receitas de Vendas de Serviços', 'Receita Operacional', 'Credora'),
    ('4.1.01.01', 'Gestão de Tráfego Pago', 'Receita Operacional', 'Credora'),
    ('4.1.01.02', 'Design e Social Media', 'Receita Operacional', 'Credora'),
    ('4.1.01.03', 'Web Design e Automações', 'Receita Operacional', 'Credora'),
    ('4.1.01.04', 'Consultoria Comercial', 'Receita Operacional', 'Credora'),
    ('4.1.01.05', 'Mentoria', 'Receita Operacional', 'Credora'),
    ('4.1.01.06', 'Implantação CRM', 'Receita Operacional', 'Credora'),
    ('4.1.01.07', 'Treinamento de Vendas', 'Receita Operacional', 'Credora'),
    ('4.1.02', 'Outras Receitas Operacionais', 'Receita Operacional', 'Credora'),

    ('4.2', 'Receitas Não Operacionais', 'Receita Não Operacional', 'Credora'),
    ('4.2.01', 'Receitas Financeiras', 'Receita Não Operacional', 'Credora'),
    ('4.2.01.01', 'Rendimentos de Aplicações', 'Receita Não Operacional', 'Credora'),
    ('4.2.01.02', 'Juros Ativos', 'Receita Não Operacional', 'Credora'),
    ('4.2.01.03', 'Variação Cambial Ativa', 'Receita Não Operacional', 'Credora'),
    ('4.2.02', 'Ganho na Venda de Ativo', 'Receita Não Operacional', 'Credora'),
    ('4.2.03', 'Recuperação de Despesas', 'Receita Não Operacional', 'Credora'),

    ('4.8', 'Deduções da Receita Bruta', 'Receita', 'Devedora'),
    ('4.8.01', 'Devoluções e Cancelamentos', 'Receita', 'Devedora'),
    ('4.8.02', 'Descontos Incondicionais', 'Receita', 'Devedora'),
    ('4.8.03', 'Impostos sobre Receita Bruta', 'Receita', 'Devedora'),

    -- 5. DESPESAS E CUSTOS
    ('5', 'Despesas', 'Despesa', 'Devedora'),
    ('5.0', 'Custos', 'Custo', 'Devedora'),
    ('5.0.01', 'Custo dos Serviços Prestados', 'Custo', 'Devedora'),
    ('5.0.02', 'Custo das Mercadorias Vendidas', 'Custo', 'Devedora'),
    ('5.0.03', 'Custo de Implantação de Projetos', 'Custo', 'Devedora'),

    ('5.1', 'Despesas Operacionais', 'Despesa Operacional', 'Devedora'),
    ('5.1.01', 'Despesas com Pessoal', 'Despesa Operacional', 'Devedora'),
    ('5.1.01.01', 'Salários e Ordenados', 'Despesa Operacional', 'Devedora'),
    ('5.1.01.02', 'Salários - CEO', 'Despesa Operacional', 'Devedora'),
    ('5.1.01.03', 'Encargos Sociais', 'Despesa Operacional', 'Devedora'),
    ('5.1.01.04', 'Benefícios', 'Despesa Operacional', 'Devedora'),
    ('5.1.01.05', 'Vale Transporte', 'Despesa Operacional', 'Devedora'),
    ('5.1.01.06', 'Vale Refeição', 'Despesa Operacional', 'Devedora'),
    ('5.1.01.07', 'Plano de Saúde', 'Despesa Operacional', 'Devedora'),

    ('5.1.02', 'Despesas Administrativas', 'Despesa Operacional', 'Devedora'),
    ('5.1.02.01', 'Despesas de Escritório', 'Despesa Operacional', 'Devedora'),
    ('5.1.02.02', 'Serviços de Terceiros', 'Despesa Operacional', 'Devedora'),
    ('5.1.02.03', 'Serviços Jurídicos', 'Despesa Operacional', 'Devedora'),
    ('5.1.02.04', 'Serviços de Contabilidade', 'Despesa Operacional', 'Devedora'),
    ('5.1.02.05', 'Serviços de Consultoria', 'Despesa Operacional', 'Devedora'),
    ('5.1.02.06', 'Comunicação', 'Despesa Operacional', 'Devedora'),
    ('5.1.02.07', 'Telefonia', 'Despesa Operacional', 'Devedora'),
    ('5.1.02.08', 'Internet', 'Despesa Operacional', 'Devedora'),
    ('5.1.02.09', 'Tecnologia da Informação', 'Despesa Operacional', 'Devedora'),
    ('5.1.02.10', 'Softwares e Licenças', 'Despesa Operacional', 'Devedora'),
    ('5.1.02.11', 'Manutenção de Sistemas', 'Despesa Operacional', 'Devedora'),
    ('5.1.02.12', 'Despesas com Aluguel', 'Despesa Operacional', 'Devedora'),
    ('5.1.02.13', 'Alimentação', 'Despesa Operacional', 'Devedora'),
    ('5.1.02.14', 'Energia Elétrica', 'Despesa Operacional', 'Devedora'),
    ('5.1.02.15', 'Água e Esgoto', 'Despesa Operacional', 'Devedora'),
    ('5.1.02.16', 'Despesas Operacionais Diversas', 'Despesa Operacional', 'Devedora'),

    ('5.1.03', 'Despesas Comerciais', 'Despesa Operacional', 'Devedora'),
    ('5.1.03.01', 'Marketing e Publicidade', 'Despesa Operacional', 'Devedora'),
    ('5.1.03.01.01', 'Anúncios em Mídias Digitais', 'Despesa Operacional', 'Devedora'),
    ('5.1.03.01.02', 'Facebook Ads', 'Despesa Operacional', 'Devedora'),
    ('5.1.03.01.03', 'Google Ads', 'Despesa Operacional', 'Devedora'),
    ('5.1.03.01.04', 'LinkedIn Ads', 'Despesa Operacional', 'Devedora'),
    ('5.1.03.01.05', 'Produção de Conteúdo', 'Despesa Operacional', 'Devedora'),
    ('5.1.03.01.06', 'Blogs', 'Despesa Operacional', 'Devedora'),
    ('5.1.03.01.07', 'Vídeos', 'Despesa Operacional', 'Devedora'),
    ('5.1.03.01.08', 'E-books', 'Despesa Operacional', 'Devedora'),
    ('5.1.03.01.09', 'Eventos e Feiras', 'Despesa Operacional', 'Devedora'),
    ('5.1.03.01.10', 'Materiais Promocionais', 'Despesa Operacional', 'Devedora'),
    ('5.1.03.02', 'Comissões de Vendas', 'Despesa Operacional', 'Devedora'),
    ('5.1.03.02.01', 'Comissão Equipe Interna', 'Despesa Operacional', 'Devedora'),
    ('5.1.03.02.02', 'Comissão Representantes', 'Despesa Operacional', 'Devedora'),
    ('5.1.03.03', 'Viagens e Representação', 'Despesa Operacional', 'Devedora'),

    ('5.1.04', 'Treinamento e Capacitação', 'Despesa Operacional', 'Devedora'),
    ('5.1.04.01', 'Treinamentos e Capacitação', 'Despesa Operacional', 'Devedora'),
    ('5.1.04.02', 'Desenvolvimento Contínuo', 'Despesa Operacional', 'Devedora'),
    ('5.1.04.03', 'Responsabilidade Social', 'Despesa Operacional', 'Devedora'),
    ('5.1.05', 'Depreciação e Amortização', 'Despesa Operacional', 'Devedora'),

    ('5.2', 'Despesas Não Operacionais', 'Despesa Não Operacional', 'Devedora'),
    ('5.2.01', 'Despesas Financeiras', 'Despesa Não Operacional', 'Devedora'),
    ('5.2.01.01', 'Juros e Encargos Financeiros', 'Despesa Não Operacional', 'Devedora'),
    ('5.2.01.02', 'Tarifas Bancárias', 'Despesa Não Operacional', 'Devedora'),
    ('5.2.01.03', 'Variação Cambial Passiva', 'Despesa Não Operacional', 'Devedora'),
    ('5.2.01.04', 'IOF', 'Despesa Não Operacional', 'Devedora'),
    ('5.2.02', 'Outras Despesas Não Operacionais', 'Despesa Não Operacional', 'Devedora'),

    ('5.9', 'Ajustes e Não Dedutíveis', 'Despesa', 'Devedora'),
    ('5.9.01', 'Multas Não Dedutíveis', 'Despesa', 'Devedora'),
    ('5.9.02', 'Doações Não Dedutíveis', 'Despesa', 'Devedora'),
    ('5.9.03', 'Ajustes de Inventário', 'Despesa', 'Devedora'),

    -- 9. CONTROLE GERENCIAL
    ('9', 'Controles Gerenciais', 'Controle', 'Devedora'),
    ('9.1', 'Centros de Custo', 'Controle', 'Devedora'),
    ('9.1.01', 'Centro de Custo Administrativo', 'Controle', 'Devedora'),
    ('9.1.02', 'Centro de Custo Comercial', 'Controle', 'Devedora'),
    ('9.1.03', 'Centro de Custo Operações', 'Controle', 'Devedora'),
    ('9.2', 'Projetos', 'Controle', 'Devedora'),
    ('9.2.01', 'Projeto A', 'Controle', 'Devedora'),
    ('9.2.02', 'Projeto B', 'Controle', 'Devedora'),
    ('9.3', 'Contas Transitórias', 'Controle', 'Devedora'),
    ('9.3.01', 'Conta Transitória de Conciliação Bancária', 'Controle', 'Devedora')
)
INSERT INTO finance.plano_de_contas (codigo, nome, tipo, natureza, ativo)
SELECT codigo, nome, tipo, natureza, TRUE
FROM seed
ON CONFLICT (codigo) DO UPDATE
SET
  nome = EXCLUDED.nome,
  tipo = EXCLUDED.tipo,
  natureza = EXCLUDED.natureza,
  ativo = TRUE,
  updated_at = NOW();

